### ISSUE TITLE
How to keep VirtualParameters up to date

### ISSUE THREAD

**Issue by noorzaie** [genieacs/genieacs#285] opened 2018-01-29 20:27 UTC
How can I keep VirtualParameters updating. for example I want to keep PeriodicInformInterval in VirtualParamters. But when I change PeriodicInformInterval on my device, its VirtualParameter doesn't update.

**Comment by zaidka** [comment] 2018-01-30 00:30
I'm seriously considering closing the issue tracker because it's being abused like this. You already know that this isn't the right place for this because you've posted here before and been asked to take it to the mailing list. I don't just mean you specifically; many of the posts here are people misusing it and being asked to use the mailing list instead. I don't understand why some refuse to read the very short and prominently placed (and highlighted) guidelines when opening an issue. Or that even after being told this isn't the right place they continue to post requests that don't belong here.

It's very simple really: if you *need help*, post to the mailing list. If you appreciate the project and would like *to help* by reporting what you're fairly confident is a bug in GenieACS, by all means post here.

Anybody has any suggestions how to deal with this? What I'm thinking is maybe close this issue tracker and create another mailing list for dev related discussions such as bugs and feature requests and the likes. However, an active Github page is a sign of a healthy and maintained project, not to mention we'd lose the conveniences of an issue tracker.

**Comment by noorzaie** [comment] 2018-01-30 06:49
The

**Comment by noorzaie** [comment] 2018-01-30 06:57
The mailing list has a weak interface and it is too hard to work with. But it is very common to ask questions about projects, using issue tracker. If issue tracker is just for bugs, then can you explain what is usage of labels in issue tracker? There is different labels for handling different posts in issue tracker: bug, question, help wanted, ... . Please don't try to change GitHub laws.

**Comment by okraits** [comment] 2018-01-30 07:12
@zaidka has clearly stated that the issue tracker should be used only for bug reports or for issues which are suspected to be a bug. And the [CONTRIBUTING](https://github.com/genieacs/genieacs/blob/master/CONTRIBUTING.md) document also clearly states that.

It's @zaidka's decision to use the issue tracker that way and GenieACS is by far not the only project which has such a guideline.

@zaidka I guess there will always be people violating that rule. And even if we have separate mailing lists for users and developers there will still be people posting to the wrong mailing list because they don't know better or something else. 
I would suggest to close all those issues which are not bug reports - because it's hard to keep track of open bugs if there are dozens of false pending bug reports.

**Closed** 2018-01-30 07:18 UTC

**Comment by zaidka** [comment] 2018-01-30 08:41
> If issue tracker is just for bugs, then can you explain what is usage of labels in issue tracker?

The issue tracker can certainly be used as as a general forum replacing the existing mailing list. The reasons I'd rather not use it for that are:

- It requires follow up to make sure issues are closed.

- Given the small community, I think a mailing list is the better choice because it encourages participation more than a forum-like system like Github Issues.

- Not entirely sure why, but I find that posts in the mailing list are, well, let's just say more effort is put into writing them.

> I would suggest to close all those issues which are not bug reports

My concern with that is that it might give off a negative vibe, not just to the poster but to anybody who stumbles upon that page in the future.

**Comment by okraits** [comment] 2018-01-30 09:28
I'm not proposing that such issues should be closed without a comment. The typical case is that the poster is directed towards the mailing list, then the issue is never picked up again. You can as well close it then.
